Extra git config
mysociety/action-git-pusher pull request #4
Opened 2023-11-17 16:50 UTC by ajparsons

Adds an extra config option.

This allows github actions that can force push back to git.mysociety.org. Means history can be rewritten through a github only workflow. 

e.g. https://github.com/mysociety/twfy-votes/blob/main/.github/workflows/mirror_manual.yml

2023-11-20 08:58 UTC, sagepe requested changes
Other than adjusting the tag used in the example, looks good.

2023-11-20 08:58 UTC, sagepe commented on README.md
> +      uses: mysociety/action-git-pusher@v1.0.0
This tag won't have the necessary commits so this example is potentially misleading. Maybe we should tag this 1.2.0 after the merge and use that in the example?

2023-11-22 15:34 UTC, ajparsons commented on README.md
> +      uses: mysociety/action-git-pusher@v1.0.0
I've updated the refs in the readme - just needs a new release when merged.

2024-06-20 08:23 UTC, ajparsons commented
Catching up on old small tasks - would you mind if I merged and then did the release for a new version?

2024-06-21 08:00 UTC, sagepe approved these changes

2024-06-21 08:00 UTC, sagepe commented
Go for it!

2024-06-21 08:48 UTC, merged